version: "3.8"

services:
  db:
    image: postgres:alpine3.20
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    volumes:
      - ./postgres:/app/subscribe_api
    ports:
      - "7080:5432"